[book]
authors = ["TCS@SUSTech"]
language = "zh-cn"
multilingual = false
src = "src"
title = "理论计算机科学导论"

[output.html]
site-url = "/intro-to-tcs-zh-cn"
default-theme = "black"
preferred-dark-theme = "black"
git-repository-url = "https://github.com/sustech-tcs/intro-to-tcs-zh-cn"
git-repository-icon = "fa-github"
mathjax-support = true
additional-js = ["mermaid.min.js", "mermaid-init.js"]
smart-puncadditional-css = ["./mdbook-admonish.css"]

[output.html.fold]
enable = true
level = 0

[output.html.playground]
editable = false

[preprocessor.mathpunc]
before = ["katex"]

[preprocessor.katex]
after = ["links"]
macros = "./macros.txt"
include-src = true
trust = true

[preprocessor.toc]
renderer = ["html"]

[preprocessor.mermaid]

[preprocessor.numthm]
custom_environments = [
  ["eqc", "式", "**"],
  ["thmc", "定理", "**"],
  ["lemc", "引理", "**"],
  ["algc", "算法", "**"]
]

[preprocessor.numeq]

[preprocessor.footnote]
after = ["numthm"]

[preprocessor.admonish]
command = "mdbook-admonish"
assets_version = "3.1.0" # do not edit: managed by `mdbook-admonish install`
after = ["links"]
