[book]
authors = ["TCS@SUSTech"]
language = "zh-cn"
multilingual = false
src = "src"
title = "理论计算机科学导论"

[output.html]
site-url = "/intro-to-tcs-zh-cn"
default-theme = "black"
preferred-dark-theme = "black"
git-repository-url = "https://github.com/sustech-tcs/intro-to-tcs-zh-cn"
git-repository-icon = "fa-github"
mathjax-support = true
additional-js = ["mermaid.min.js", "mermaid-init.js"]
smart-puncadditional-css = ["./mdbook-admonish.css"]

[output.html.playground]
editable = true

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[preprocessor.mathpunc]
before = ["katex"]

[preprocessor.katex]
trust = true
after = ["links"]
macros = "./macros.txt"
include-src = true

[preprocessor.numeq]

[preprocessor.callouts]

[preprocessor.numthm]
custom_environments = [
  ["eq", "Equation", "**"],
  ["thm", "定理", "**"],
  ["lem", "引理", "**"],
  ["alg", "算法", "**"]
]

[preprocessor.footnote]
after = ["numthm"]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.admonish]
command = "mdbook-admonish"
assets_version = "3.1.0" # do not edit: managed by `mdbook-admonish install`

