[book]
authors = ["TCS@SUSTech"]
language = "zh-cn"
multilingual = false
src = "src"
title = "理论计算机科学导论"


[output.html]
site-url = "/intro-to-tcs-zh-cn"
default-theme = "black"
preferred-dark-theme = "black"
git-repository-url = "https://github.com/sustech-tcs/intro-to-tcs-zh-cn"
git-repository-icon = "fa-github"


[output.html.playground]
editable = true

[preprocessor.katex]
after = ["links"]
output = "mathml"